services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn final_akio_apis:app --host 0.0.0.0 --port 10000"
